language: node_js
node_js:
  - 0.8
  - 0.9
  - 0.10
before_script:
  - npm install -g grunt-cli
scripts: 
  test: grunt travis --verbose
notifications:
  email:
    - fabiomcosta@gmail.com
    - johnvoloski@gmail.com
